package vrcafe.models;

import com.fasterxml.jackson.annotation.JsonView;

import java.util.Random;

public class Author {

    @JsonView(ViewClasses.Shallow.class)
    private long id = 0L;     // identification of an Author
                              // unique id-s are generated by the back-end persistence layer

    @JsonView(ViewClasses.Shallow.class)
    private String lastName;
    @JsonView(ViewClasses.Summary.class)
    private String initials;

    public Author() {
    }

    public Author(long id) {
        this.id = id;
    }
    public Author(long id, String lastName) {
        this(id);
        this.lastName = lastName;
    }

    private static Random randomizer = new Random();
    public static Author createSample(long id) {
        Author newAuthor = new Author(id);

        // pick one of below list of samples of last names
        newAuthor.setLastName(lastNames[randomizer.nextInt(Author.lastNames.length)]);
        // construct random two-character initials followed by dots.
        newAuthor.setInitials(
                Character.toString((int)'A'+randomizer.nextInt(26)) + "." +
                Character.toString((int)'A'+randomizer.nextInt(26)) + ".");

        return newAuthor;
    }

    private static String[] lastNames = {
            "Dijkstra", "Penrose", "Pinker", "Griffith", "Harari", "Bregman", "Mulisch", "Ruyslinck"
    };

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getInitials() {
        return initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }
}
