package vrcafe.models;

import com.fasterxml.jackson.annotation.JsonView;

import java.time.LocalDate;
import java.util.Random;

public class Book {

    public enum Type {
        Unspecified,
        Hardcover,
        Paperback,
        eBook,
        Magazine;
    };

    @JsonView(ViewClasses.Shallow.class)
    private long id = 0L;       // identification of a Book
                                // unique id-s are generated by the back-end persistence layer

    @JsonView(ViewClasses.Summary.class)
    private Author author;

    @JsonView(ViewClasses.Shallow.class)
    private String title;

    @JsonView(ViewClasses.Shallow.class)
    private Type type;

    private LocalDate publicationDate;

    private long isbn;
    private double price;

    public Book() {
    }

    public Book(long id) {
        this.id = id;
    }

    public Book(long id, String title) {
        this(id);
        this.title = title;
    }

    private static Random randomizer = new Random();

    public static Book createSample(long id, Author author) {
        Book newBook = new Book(id);
        newBook.setAuthor(author);

        // TODO add some realistic random sample data to the new book
        newBook.setIsbn(9780130000000L + randomizer.nextInt(100000));
        newBook.setTitle("A" +
                titleAdjectives1[randomizer.nextInt(titleAdjectives1.length)]
                + ", " + titleAdjectives2[randomizer.nextInt(titleAdjectives2.length)]
                + " book about " + titleTopics[randomizer.nextInt(titleTopics.length)]);

        newBook.setType(Type.values()[1+randomizer.nextInt(Type.values().length-1)]);

        newBook.setPublicationDate(LocalDate.now().minusMonths(randomizer.nextInt(1000)));

        newBook.setPrice(3.0 + 0.05 * randomizer.nextInt(3000));

        return newBook;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public LocalDate getPublicationDate() {
        return publicationDate;
    }

    public void setPublicationDate(LocalDate publicationDate) {
        this.publicationDate = publicationDate;
    }

    public long getIsbn() {
        return isbn;
    }

    public void setIsbn(long isbn) {
        this.isbn = isbn;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    static String[] titleAdjectives1 = {
            " unique", " modern", " small", " colourful", " new", " cheap"
    };
    static String[] titleAdjectives2 = {
            "temptatious", "dull", "boring", "exiting", "original", "interesting", "seductive"
    };

    static String[] titleTopics = {
            "sports", "politics", "cooking", "health", "science", "music", "mankind", "nature"
    };
}
