package appsb.models;

public class Author {

    private long id = 0L;     // identification of an Author
                              // unique id-s are generated by the back-end persistence layer
    private String lastName;
    private String initials;

    public Author() {
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getInitials() {
        return initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }
}
