package appsb.models;

import java.time.LocalDate;

public class Book {

    public enum Type {
        Unspecified,
        Hardcover,
        Paperback,
        eBook,
        Magazine;
    };

    private long id = 0L;       // identification of a Book
                                // unique id-s are generated by the back-end persistence layer
    private Author author;
    private String title;
    private LocalDate publicationDate;
    private long isbn;
    private double price;

    public Book() {
    }

    public Book(long id) {
        this.id = id;
    }

    public Book(long id, String title) {
        this(id);
        this.title = title;
    }

    public static Book createSample(long id, Author author) {
        Book newBook = new Book(id);
        newBook.setAuthor(author);

        // TODO add some realistic random sample data to the new book

        return newBook;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDate getPublicationDate() {
        return publicationDate;
    }

    public void setPublicationDate(LocalDate publicationDate) {
        this.publicationDate = publicationDate;
    }

    public long getIsbn() {
        return isbn;
    }

    public void setIsbn(long isbn) {
        this.isbn = isbn;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
